pipeline:
  name: cache check22 dec
  identifier: cache_check22_dec
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: nestedStageDemo
          versionLabel: v1
    - stage:
        name: stage2
        identifier: stage2
        template:
          templateRef: nestedStageDemo
          versionLabel: v1
