pipeline:
  name: caching pipe 16 dec
  identifier: caching_pipe_16_dec
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1234
        identifier: stage1
        template:
          templateRef: k8sMigration12Dec
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              serviceConfig:
                serviceDefinition:
                  type: Kubernetes
                  spec:
                    manifests:
                      - manifest:
                          identifier: manifest1
                          type: Kustomize
                          spec:
                            store:
                              type: Github
                              spec:
                                repoName: <+input>
              infrastructure:
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: <+input>
    - stage:
        name: stagge2
        identifier: stagge2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: abc
                  identifier: abc
                  spec:
                    url: <+input>
                    method: GET
                    headers: []
                    outputVariables: []
                    requestBody: <+input>
                  timeout: 10s
        tags: {}
