pipeline:
  name: cache pipe2 dec15
  identifier: cahce_pipe2_dec15
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: stage1
            identifier: stage1
            template:
              templateRef: DeolyStage14Dec
              versionLabel: v1
              templateInputs:
                type: Deployment
                spec:
                  infrastructure:
                    infrastructureDefinition:
                      type: KubernetesGcp
                      spec:
                        connectorRef: <+input>
                        cluster: <+input>
                        namespace: <+input>
        - stage:
            name: stage2
            identifier: stage2
            template:
              templateRef: k8sMigration12Dec
              versionLabel: "1"
              templateInputs:
                type: Deployment
                spec:
                  serviceConfig:
                    serviceDefinition:
                      type: Kubernetes
                      spec:
                        manifests:
                          - manifest:
                              identifier: manifest1
                              type: Kustomize
                              spec:
                                store:
                                  type: Github
                                  spec:
                                    repoName: <+input>
                  infrastructure:
                    infrastructureDefinition:
                      type: KubernetesDirect
                      spec:
                        connectorRef: <+input>
                        namespace: <+input>
        - stage:
            name: stage3
            identifier: stage3
            template:
              templateRef: StageDeploy12Dec
              versionLabel: "1"
    - stage:
        name: stage4-1
        identifier: stage4
        template:
          templateRef: account.Deploy_SecretStore
          versionLabel: v1.0
          templateInputs:
            type: Deployment
            spec:
              serviceConfig:
                serviceRef: <+input>
                serviceDefinition:
                  type: Kubernetes
                  spec:
                    manifests:
                      - manifest:
                          identifier: acc1
                          type: HelmChart
                          spec:
                            store:
                              type: Http
                              spec:
                                connectorRef: <+input>
                            chartName: <+input>
                            chartVersion: <+input>
              infrastructure:
                environmentRef: <+input>
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: <+input>
