pipeline:
  name: kn
  identifier: kn
  projectIdentifier: NGPipeAutoVariablesHSJyadQNMx
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: dfg
        identifier: dfg
        template:
          templateRef: sdf
          versionLabel: asdfadsf
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: sdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
