pipeline:
  name: 17oct git sync
  identifier: oct_git_sync
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S12
        identifier: S12
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 'update'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: step2
                  identifier: step2
                  template:
                    templateRef: step17OCtBranch
                    versionLabel: "1"
                    templateInputs:
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
        tags: {}
