pipeline:
  name: pipe123
  identifier: pipe123
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: cvcv
                  identifier: cvcv
                  template:
                    templateRef: stepGroupTemplate1
                    versionLabel: v1
                    gitBranch: prakhar-demo-1
                    templateInputs:
                      steps:
                        - step:
                            identifier: shell
                            template:
                              templateInputs:
                                type: ShellScript
                                timeout: <+input>
        tags: {}
    - stage:
        name: S2
        identifier: S2
        tags: {}
        template:
          templateRef: cdTemplate
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          sources:
                            - identifier: artifactTemplate
                              template:
                                templateInputs:
                                  type: DockerRegistry
                                  spec:
                                    tag: <+input>
                                    digest: <+input>
              execution:
                steps:
                  - step:
                      identifier: Delete
                      template:
                        templateInputs:
                          type: K8sDelete
                          spec:
                            deleteResources:
                              type: ResourceName
                              spec:
                                resourceNames: <+input>
              environments:
                metadata:
                  parallel: <+input>
                values: <+input>
                filters:
                  - identifier: afdvd
                    type: tags
                    spec:
                      tags: <+input>
            variables:
              - name: adscasdc
                type: String
                value: <+input>
