pipeline:
  name: pipelineRemote31Jan
  identifier: pipelineRemote31Jan
  projectIdentifier: donotdeleteflexiTemplate
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s234
        identifier: s234
        tags: {}
        template:
          templateRef: stageRemoteTemplate1
          versionLabel: v123
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - stepGroup:
                      identifier: sg1
                      template:
                        templateInputs:
                          steps:
                            - step:
                                identifier: s234
                                template:
                                  templateInputs:
                                    type: ShellScript
                                    spec:
                                      source:
                                        type: Inline
                                        spec:
                                          script: <+input>
                          variables:
                            - name: var1
                              type: String
                              value: <+input>.allowedValues(test,test2)
                  - insert:
                      identifier: step1
                      steps:
                        - step:
                            type: ShellScript
                            name: ShellScript_1
                            identifier: ShellScript_1
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: <+input>
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
            variables:
              - name: var12
                type: String
                value: <+input>
              - name: var234
                type: String
                value: <+input>
                - name: var2345
                type: String
                value: <+input>
