pipeline:
  name: pipelineRemote12feb
  identifier: pipelineRemote12feb
  tags: {}
  template:
    templateRef: pipelineTemplate12Feb
    versionLabel: "1"
    gitBranch: main-patch
    templateInputs:
      stages:
        - stage:
            identifier: S1
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
        - stage:
            identifier: s2
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: ShellScript_1
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
