pipeline:
  name: pipeline12SrtageTemp
  identifier: pipeline12SrtageTemp
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: Stage12Template
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              execution:
                steps:
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
            strategy: <+input>
  variables:
    - name: var23
      type: String
      description: ""
      required: false
      value: <+input>.selectOneFrom(test1,test2)
