pipeline:
  name: pipeline execution improvement
  identifier: pipeline_execution_improvement
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: account.stage_1
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: t2
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
                  - step:
                      identifier: t3
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: account.stage_2
          versionLabel: v2
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: t1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
                  - step:
                      identifier: t2
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
                  - step:
                      identifier: t3
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
    - stage:
        name: s3
        identifier: s3
        template:
          templateRef: account.stage_3
          versionLabel: v3
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: t1
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
                  - step:
                      identifier: rt2
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
    - stage:
        name: s4
        identifier: s4
        template:
          templateRef: account.stage_4
          versionLabel: v4
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: t1
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
                  - step:
                      identifier: t8
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
