pipeline:
  name: testparent28Feb
  identifier: testparent28Feb
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Pipeline
        spec:
          org: Pipelines_NonK8s_Org_NG
          project: AmitTest
          pipeline: testRemoteChild
