pipeline:
  name: testParentMarch22
  identifier: testParentMarch22
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Pipeline
        spec:
          org: Pipelines_NonK8s_Org_NG
          pipeline: testChildMArch22
          project: AmitTest
          inputs:
            identifier: testChildMArch22
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: s1
                      type: Custom
                      spec:
                        execution:
                          steps:
                            - step:
                                identifier: ShellScript_1
                                type: ShellScript
                                spec:
                                  source:
                                    type: Inline
                                    spec:
                                      script: <+input>
