pipeline:
  name: testparent
  identifier: testparent
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s2
        identifier: s2
        description: ""
        type: Pipeline
        spec:
          org: Pipelines_NonK8s_Org_NG
          pipeline: testChild
          project: AmitTest
