pipeline:
  name: testONPremPipeline
  identifier: testONPremPipeline
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: Ser4
        identifier: Ser4
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ste3
                  identifier: ste3
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
