pipeline:
  name: test gitsync
  identifier: test_gitsync
  projectIdentifier: amitTestGitX
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S12
        identifier: S12
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: 123
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
